version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      INSTAGRAM_ACCESS_TOKEN: ""
      USER_ID_TO_MONITOR: ""
      SLACK_INCOMING_WEBHOOK_URL: ""

